name: SimpleEssential
main: cn.citycraft.SimpleEssential.SimpleEssential
website: http://ci.citycraft.cn:8800/jenkins/job/SimpleEssential/
version: 1.0
commands:
  simpleessential:
    description: 简单基础插件
    aliases: [se,sme]
    usage: §6使用§a/se help §6查看帮助!
    permission: se.*
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  tpa: 
    description: 传送到目标玩家
    aliases: [setps,smetpa]
    usage: §6使用§a/tpa <player> §6传送到目标玩家!
    permission: se.tpa
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  tphere: 
    description: 邀请目标玩家
    aliases: [tph]
    usage: §6使用§a/tphere <player> §6邀请目标玩家!
    permission: se.tphere
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  tpaccept: 
    description: 接受传送或邀请
    aliases: [tpok]
    usage: §6使用§a/tpaccept §6接受传送或邀请!
    permission: se.tpaccept
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  tpdeny: 
    description: 拒绝传送或邀请
    aliases: [tpno]
    usage: §6使用§a/tpdeny §6拒绝传送或邀请!
    permission: se.tpdeny
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  back: 
    description: 回到上一个TP地点
    aliases: [seback]
    usage: §6使用§a/back §6回到上一个TP地点!
    permission: se.back
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  top: 
    description: 传送到最高方块
    aliases: [setop]
    usage: §6使用§a/top §6传送到当前位置最高方块!
    permission: se.top
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  home: 
    description: 传送到家里
    aliases: [sehome]
    usage: §6使用§a/home §6传送到家里!
    permission: se.home
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  sethome: 
    description: 设置当前位置为家
    aliases: [sesethome]
    usage: §6使用§a/sethome §6设置当前位置为家!
    permission: se.sethome
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  suicide: 
    description: 自杀
    aliases: [sesuicide,sd]
    usage: §6使用§a/suicide §6结束自己的生命!
    permission: se.suicide
    permission-message: §c你没有 <permission> 的权限来执行此命令!
  hat: 
    description: 帽子
    aliases: [sehat]
    usage: §6使用§a/hat §6把手上的物品带在头上!
    permission: se.hat
    permission-message: §c你没有 <permission> 的权限来执行此命令!
permissions: 
  se.*:
    description: 简单基础插件所有权限!
    default: op
    children:
      se.user: true
  se.user: 
    description: 简单基础插件玩家权限!
    default: true
    children:
      se.tpa: true
      se.tphere: true
      se.tpaccept: true
      se.tpdeny: true
      se.back: true
      se.sethome: true
      se.home: true
      se.suicide: true
      se.hat: true

